#ifndef CST_H
#define CST_H

#include "lexer.h"

typedef enum {
    CST_TRANSLATION_UNIT,
    CST_EXTERNAL_DECLARATION,
    CST_FUNCTION_DEFINITION,
    CST_DECLARATION,
    CST_DECL_SPECIFIERS,
    CST_STORAGE_CLASS,
    CST_TYPE_QUALIFIER,
    CST_TYPE_SPECIFIER,
    CST_STRUCT_OR_UNION,
    CST_ENUM_SPECIFIER,
    CST_INIT_DECLARATOR,
    CST_DECLARATOR,
    CST_POINTER,
    CST_DIRECT_DECLARATOR,
    CST_PARAMETER_LIST,
    CST_PARAMETER_DECLARATION,
    CST_INITIALIZER,
    CST_INITIALIZER_LIST,
    CST_DESIGNATED_INITIALIZER,
    CST_STATEMENT,
    CST_COMPOUND_STMT,
    CST_IF_STMT,
    CST_SWITCH_STMT,
    CST_WHILE_STMT,
    CST_DO_WHILE_STMT,
    CST_FOR_STMT,
    CST_GOTO_STMT,
    CST_CONTINUE_STMT,
    CST_BREAK_STMT,
    CST_RETURN_STMT,
    CST_LABELED_STMT,
    CST_EXPRESSION_STMT,
    CST_PRIMARY_EXPR,
    CST_POSTFIX_EXPR,
    CST_ARGUMENT_LIST,
    CST_UNARY_EXPR,
    CST_CAST_EXPR,
    CST_MULTIPLICATIVE_EXPR,
    CST_ADDITIVE_EXPR,
    CST_SHIFT_EXPR,
    CST_RELATIONAL_EXPR,
    CST_EQUALITY_EXPR,
    CST_AND_EXPR,
    CST_EXCLUSIVE_OR_EXPR,
    CST_INCLUSIVE_OR_EXPR,
    CST_LOGICAL_AND_EXPR,
    CST_LOGICAL_OR_EXPR,
    CST_CONDITIONAL_EXPR,
    CST_ASSIGNMENT_EXPR,
    CST_EXPRESSION,
    CST_TYPE_NAME,
    CST_SPECIFIER_QUALIFIER_LIST,
    CST_ABSTRACT_DECLARATOR,
    CST_DIRECT_ABSTRACT_DECLARATOR,


    CST_IDENTIFIER,
    CST_INT_CONST,
    CST_FLOAT_CONST,
    CST_CHAR_CONST,
    CST_STRING_LITERAL,

    CST_AUTO, CST_BREAK, CST_CASE, CST_CHAR, CST_CONST, CST_CONTINUE,
    CST_DEFAULT, CST_DO, CST_DOUBLE, CST_ELSE, CST_ENUM, CST_EXTERN,
    CST_FLOAT, CST_FOR, CST_GOTO, CST_IF, CST_INT, CST_LONG, CST_REGISTER,
    CST_RETURN, CST_SHORT, CST_SIGNED, CST_SIZEOF, CST_STATIC, CST_STRUCT,
    CST_SWITCH, CST_TYPEDEF, CST_UNION, CST_UNSIGNED, CST_VOID, CST_VOLATILE,
    CST_WHILE,
    CST_LPAREN, CST_RPAREN, CST_LBRACKET, CST_RBRACKET, CST_LBRACE, CST_RBRACE,
    CST_SEMICOLON, CST_COMMA, CST_DOT, CST_AMPERSAND, CST_ASTERISK, CST_PLUS,
    CST_MINUS, CST_TILDE, CST_EXCLAM, CST_SLASH, CST_PERCENT, CST_LESS, CST_GREATER,
    CST_HAT, CST_PIPE, CST_QUESTION, CST_COLON, CST_EQUALS,
    CST_ELLIPSIS, CST_ARROW, CST_INCREMENT, CST_DECREMENT, CST_LEFT_SHIFT,
    CST_RIGHT_SHIFT, CST_LE_OP, CST_GE_OP, CST_EQ_OP, CST_NE_OP,
    CST_AND_OP, CST_OR_OP,
    CST_EOF,
    CST_ERROR
} CstKind;


typedef struct CstNode CstNode;

struct CstNode {
    CstKind kind;
    int line;

    union {
        struct {
            const char* start;
            int length;
        } token;

        struct {
            CstNode** children;
            int count;
            int capacity;
        } rule;
    } u;
};


CstNode* cst_make_terminal(CstKind kind, const char* start, int length, int line);

CstNode* cst_make_rule(CstKind kind, int line);


void cst_add_child(CstNode* parent, CstNode* child);


void cst_free(CstNode* node);

#endif